"""Add RBAC and Soft Delete

Revision ID: bf1381a07e4c
Revises: 72bdc995ef53
Create Date: 2026-03-19 01:18:36.456717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1381a07e4c'
down_revision: Union[str, Sequence[str], None] = '72bdc995ef53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('quizzes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('quizzes', 'is_active')
    op.drop_column('lectures', 'is_active')
    # ### end Alembic commands ###
